### ISSUE TITLE
what dependancies do i need to build it on opi5 arm64

### ISSUE THREAD

**Issue by develperbayman** [ice-wm/icewm#172] opened 2024-08-14 20:02 UTC
i have tried then i asked ai but all i got is 
on debian bookworm server from opi5 downloads

```
orangepi@orangepi5:~/Downloads/icewm-master$ ./autogen.sh
autoreconf: export WARNINGS=
autoreconf: Entering directory '.'
autoreconf: running: autopoint --force
Copying file po/Makefile.in.in
autoreconf: running: aclocal --force -I m4
autoreconf: configure.ac: tracing
autoreconf: configure.ac: not using Libtool
autoreconf: configure.ac: not using Intltool
autoreconf: configure.ac: not using Gtkdoc
autoreconf: running: /usr/bin/autoconf --force
configure.ac:83: error: possibly undefined macro: AC_DISABLE_STATIC
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
autoreconf: error: /usr/bin/autoconf failed with exit status: 1
orangepi@orangepi5:~/Downloads/icewm-master$ 
```

**Comment by gijsbers** [comment] 2024-08-14 20:14
Duplicate of bbidulock/icewm#342.

Please follow the instructions from the website.

**Comment by develperbayman** [comment] 2024-08-14 21:23
thank you i did not see that

**Closed** 2024-08-15 20:13 UTC
Labels: duplicate
